version: '3.8'

services:
  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: desafio_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  # Serviço do PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio_php
    volumes:
      - ./src:/var/www/html

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: desafio_mysql
    restart: always
    environment:
      MYSQL_DATABASE: desafio_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      # Mapeia nosso volume de dados do mysql
      - ./mysql_data:/var/lib/mysql
      # Mapeia nosso script de inicialização para a pasta especial dentro do contêiner.
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: